version: '3.8'

services:
  # Serviço de Banco de Dados (Mantenha este igual)
  db:
    image: postgis/postgis:16-3.4-alpine
    container_name: easyapigis_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: easyapigis_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - easyapi_net

  # NOVO: Serviço Backend
  backend:
    build: ./backend
    container_name: easyapigis_backend
    volumes:
      - ./backend/app:/app/app # Hot-reload no Windows funciona bem aqui
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/easyapigis_db
    depends_on:
      - db
    networks:
      - easyapi_net

volumes:
  postgres_data:

networks:
  easyapi_net:
    driver: bridge