version: '3.8'

services:
  # Serviço de Banco de Dados Espacial
  db:
    image: postgis/postgis:16-3.4-alpine
    container_name: easyapigis_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: easyapigis_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - easyapi_net

  # O Backend será configurado no próximo passo, mas já deixamos o placeholder
  # O Frontend será configurado no próximo passo

volumes:
  postgres_data:

networks:
  easyapi_net:
    driver: bridge