services:
  # 1. Banco de Dados
  db:
    image: postgis/postgis:16-3.4-alpine
    container_name: easyapigis_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: easyapigis_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - easyapi_net

  # 2. Backend
  backend:
    build: ./backend
    container_name: easyapigis_backend
    volumes:
      - ./backend/app:/app/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/easyapigis_db
    depends_on:
      - db
    networks:
      - easyapi_net

  # 3. Frontend (Deve estar alinhado com 'backend' e 'db')
  frontend:
    build: ./frontend
    container_name: easyapigis_frontend
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/index.html:/app/index.html
      - ./frontend/vite.config.ts:/app/vite.config.ts
      - ./frontend/tailwind.config.js:/app/tailwind.config.js
      - ./frontend/postcss.config.js:/app/postcss.config.js
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - easyapi_net

volumes:
  postgres_data:

networks:
  easyapi_net:
    driver: bridge